#!/usr/bin/env python3
"""Generate grey placeholder PNGs so the report compiles before any real image exists.

    python3 scripts/gen_figures.py reports_docs figures

Existing files are never overwritten: drop your real image in with the same
filename and it survives every rebuild. Placeholders are stamped with a PNG
text chunk ``claude-report=placeholder`` so the manifest can tell them apart
from real screenshots.
"""
from __future__ import annotations

import sys
import textwrap
from pathlib import Path
from typing import Optional

from PIL import Image, ImageDraw, ImageFont, PngImagePlugin

sys.path.insert(0, str(Path(__file__).parent))
from placeholders import scan_tree  # noqa: E402

PLACEHOLDER_KEY = "claude-report"
PLACEHOLDER_VALUE = "placeholder"

BASE_W = 1600  # px at width=1.0
BG = (238, 238, 238)
BORDER = (176, 176, 176)
SLUG_C = (90, 90, 90)
CAP_C = (130, 130, 130)

FONT_CANDIDATES = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/Library/Fonts/Arial Bold.ttf",
    "/Library/Fonts/Arial.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "C:/Windows/Fonts/arialbd.ttf",
    "C:/Windows/Fonts/arial.ttf",
    "C:/Windows/Fonts/calibrib.ttf",
)


def _font(size: int):
    for path in FONT_CANDIDATES:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                continue
    return ImageFont.load_default()


def is_placeholder(path: Path) -> Optional[bool]:
    """True if this PNG was generated by us, False if a real image, None if missing."""
    if not path.is_file():
        return None
    try:
        with Image.open(path) as im:
            if im.format == "PNG" and im.text.get(PLACEHOLDER_KEY) == PLACEHOLDER_VALUE:
                return True
            return False
    except OSError:
        return False


def make_placeholder(path: Path, slug: str, caption: str, width_frac: float) -> None:
    w = max(480, int(BASE_W * width_frac))
    h = int(w * 0.6)
    img = Image.new("RGB", (w, h), BG)
    d = ImageDraw.Draw(img)
    d.rectangle([4, 4, w - 5, h - 5], outline=BORDER, width=3)

    for x in range(-h, w, 48):
        d.line([(x, h), (x + h, 0)], fill=(228, 228, 228), width=2)

    f_slug = _font(max(22, w // 26))
    f_cap = _font(max(16, w // 42))

    lines = [("PLACEHOLDER", f_cap, CAP_C), (slug, f_slug, SLUG_C)]
    for chunk in textwrap.wrap(caption, width=48)[:3]:
        lines.append((chunk, f_cap, CAP_C))
    lines.append((f"figures/{slug}.png", f_cap, CAP_C))

    heights = [d.textbbox((0, 0), t, font=f)[3] for t, f, _ in lines]
    total = sum(heights) + 14 * (len(lines) - 1)
    y = (h - total) // 2
    for (text, font, colour), th in zip(lines, heights):
        tw = d.textbbox((0, 0), text, font=font)[2]
        d.text(((w - tw) // 2, y), text, font=font, fill=colour)
        y += th + 14

    meta = PngImagePlugin.PngInfo()
    meta.add_text(PLACEHOLDER_KEY, PLACEHOLDER_VALUE)
    img.save(path, pnginfo=meta)


def generate(root: Path, outdir: Path) -> dict:
    outdir.mkdir(parents=True, exist_ok=True)
    figs = [p for p in scan_tree(root) if p.kind == "FIG"]
    seen, created, kept_real, kept_ph = set(), 0, 0, 0

    for p in figs:
        if p.slug in seen:
            continue
        seen.add(p.slug)
        dest = outdir / f"{p.slug}.png"
        if dest.exists():
            if is_placeholder(dest):
                kept_ph += 1
            else:
                kept_real += 1
            continue
        make_placeholder(dest, p.slug, p.caption, float(p.options.get("width", 0.8)))
        created += 1

    rows = [
        "# Figures attendues",
        "",
        "| Slug | Légende | Chapitre | Largeur min. | État |",
        "|---|---|---|---|---|",
    ]
    written = set()
    counts = {"placeholder": 0, "fourni": 0, "manquant": 0}
    for p in figs:
        if p.slug in written:
            continue
        written.add(p.slug)
        dest = outdir / f"{p.slug}.png"
        flag = is_placeholder(dest)
        if flag is None:
            state = "manquant"
        elif flag:
            state = "placeholder"
        else:
            state = "fourni"
        counts[state] = counts.get(state, 0) + 1
        minw = int(1600 * float(p.options.get("width", 0.8)))
        rows.append(
            f"| `{p.slug}` | {p.caption} | {p.file} | {minw} px | {state} |"
        )
    (outdir / "MANIFEST.md").write_text("\n".join(rows) + "\n", encoding="utf-8")
    return {
        "created": created,
        "kept_placeholder": kept_ph,
        "kept_real": kept_real,
        "counts": counts,
        "manifest": str(outdir / "MANIFEST.md"),
    }


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "reports_docs")
    outdir = Path(sys.argv[2] if len(sys.argv) > 2 else "figures")
    result = generate(root, outdir)
    print(
        f"figures: {result['created']} placeholder(s) créé(s), "
        f"{result['kept_real']} image(s) réelle(s) conservée(s), "
        f"{result['kept_placeholder']} placeholder(s) conservé(s)"
    )
    print(f"manifeste: {result['manifest']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
